### ISSUE TITLE
【question】 Attempt to convert the dataset to Label Studio format using the source code coco.py

### ISSUE THREAD

**Issue by jiangtangaaaa** [HumanSignal/label-studio-converter#291]
@makseq 

Hello, sorry to bother you!
I tried to convert my dataset to a format supported by Label Studio using the source code coco.py, but after running this line of code `python label_studio_converter/imports/coco.py -i /yiliao5-1.json -o output.json` , there were no errors or output.json files generated. I would like to inquire with you about why
您好，打扰了！
我尝试用源码coco.py将我的数据集转换成Label Studio支持的格式，但是使用这行代码运行之后，没有报错也没有output.json的文件生成。我想向您咨询一下是为什么

![image](https://github.com/HumanSignal/label-studio-converter/assets/101043186/af626100-2c3a-4e36-b87d-1a6bfd675325)

**Comment by makseq** [comment]
Coco.py is not runnable file. Use 'label-studio-converter import' command for it.

**Comment by jiangtangaaaa** [comment]
> Coco.py is not runnable file. Use 'label-studio-converter import' command for it.Coco.py 是不可运行的文件。使用“label-studio-converter import”命令。

谢谢您！
